---
- hosts: cloudport
  vars_files:
    - ../vars/application.yml
    - ../vars/secrets.yml
  vars:
    app_user_uid: 777
    app_user_gid: 777
    app_user_bash_aliases: "{{ app_user_home }}/.bash_aliases"
    app_sudoers_file: "/etc/sudoers.d/{{ app_name }}"
  become: yes
  tasks:
    - name: Create application user group
      group: name={{ app_group_name }} gid={{ app_user_gid }} state=present
    - name: Create application user
      user: name={{ app_user_name }}
            uid={{ app_user_uid }}
            group={{ app_group_name }}
            groups=docker
            home={{ app_user_home }}
            shell=/bin/bash
            comment='CloudPort application user'
            state=present
    - name: Create application user home
      file: name={{ app_user_home }}
            owner={{ app_user_name }}
            group={{ app_group_name }}
            mode=0755
            state=directory
    - name: Create application user Bash aliases file
      template: src=../templates/bash_aliases.j2
                dest={{ app_user_bash_aliases }}
                owner={{ app_user_name }}
                group={{ app_group_name }}
                mode=0644
    - name: Setup MySQL application user
      mysql_user: name={{ mysql_app_username }}
                  priv=*.*:ALL
                  host=localhost
                  password={{ mysql_app_password }}
                  check_implicit_admin=no
                  login_user=root
                  login_password={{ mysql_root_password }}
                  state=present
    - name: Create MySQL application user config file
      template: src=../templates/my.cnf.j2
                dest="{{ app_user_home }}/.my.cnf"
                owner={{ app_user_name }}
                group={{ app_group_name }}
                mode=0600
    - name: Create sudoers.d config file for application user
      template: src=../templates/sudoers.d.j2
                dest={{ app_sudoers_file }}
                owner=root
                group=root
                mode=0440
                validate="visudo -c -f %s"
