---
- hosts: cloudport
  vars_files:
    - ../vars/application.yml
    - ../vars/go.yml
    - ../vars/secrets.yml
  vars:
    app_server_name: 'puma'
    app_server_bind: '127.0.0.1'
    app_server_port: 8000
    app_logrotate_conf: "/etc/logrotate.d/{{ app_name }}"
    app_server_upstart_file: "/etc/init/{{ app_name }}.conf"
    app_log_path: "/var/log/{{ app_name }}"
    app_pid_path: "/var/run/{{ app_name }}"
    app_server_out_file: "{{ app_log_path }}/{{ app_server_name }}-out.log"
    app_server_err_file: "{{ app_log_path }}/{{ app_server_name }}-err.log"
    app_server_pid_file: "{{ app_pid_path }}/{{ app_server_name }}.pid"
    app_host_file: "/etc/{{ app_name }}_hostname"
    app_pass_file: "/etc/{{ app_name }}_password"
    scheduler_name: "sidekiq"
    scheduler_upstart_file: "/etc/init/{{ scheduler_name }}.conf"
    scheduler_log_file: "{{ app_log_path }}/{{ scheduler_name }}.log"
    scheduler_pid_file: "{{ app_pid_path }}/{{ scheduler_name }}.pid"
    go_path: "{{ app_user_home }}/go/{{ go_version }}"
    path: "{{ bundle_gem_path }}/bin:{{ app_user_gem_path }}/bin:{{ go_path }}/bin:{{ go_root }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    gem_path: "{{ bundle_gem_path }}:{{ app_user_gem_path }}"
  become: yes
  tasks:
    - name: Disable hellborn Dash
      file: src=/bin/bash dest=/bin/sh owner=root group=root mode=0755 state=link force=yes
    - name: Add Brightbox PPA
      apt_repository: repo='ppa:brightbox/ruby-ng' state=present update_cache=yes
    - name: Install Ruby
      apt: pkg={{ item }} state=latest
      with_items:
        - "ruby{{ ruby_version }}"
        - "ruby{{ ruby_version }}-dev"
    - name: Create application config file
      template: src=../templates/config.j2
                dest={{ app_conf_file }}
                owner={{ app_user_name }}
                group={{ app_group_name }}
                mode=0640
    - name: Create application host file
      template: src=../templates/app_host.j2
                dest={{ app_host_file }}
                owner=root
                group={{ app_group_name }}
                mode=0644
                force=no
    - name: Create file with WWW administrator's password
      template: src=../templates/app_pass.j2
                dest={{ app_pass_file }}
                owner=root
                group={{ app_group_name }}
                mode=0640
    - name: Create Go path
      file: name={{ go_path }}
            owner={{ app_user_name }}
            group={{ app_group_name }}
            mode=0755
            state=directory
    - name: Create application log path
      file: name={{ app_log_path }}
            owner={{ app_user_name }}
            group=adm
            mode=0755
            state=directory
    - name: Create application logrotate.d config file
      template: src=../templates/logrotate.d.j2
                dest={{ app_logrotate_conf }}
                owner=root
                group=root
                mode=0644
    - name: Create application server Upstart config
      template: src=../templates/upstart/app_server.conf.j2
                dest={{ app_server_upstart_file }}
                owner=root
                group={{ app_group_name }}
                mode=0640
      notify:
        - Reload Upstart configuration
    - name: Create scheduler Upstart config
      template: src=../templates/upstart/scheduler.conf.j2
                dest={{ scheduler_upstart_file }}
                owner=root
                group={{ app_group_name }}
                mode=0640
      notify:
        - Reload Upstart configuration
    - name: Create Nginx site configuration
      template: src=../templates/nginx.site.j2
                dest=/etc/nginx/sites-available/default
                owner=root
                group=root
                mode=0644
      notify:
        - Reload Nginx
  handlers:
    - name: Reload Upstart configuration
      shell: initctl reload-configuration
    - name: Reload Nginx
      service: name=nginx state=reloaded
