---
- hosts: all
  vars_files:
    - ../vars/globals.yml
    - ../vars/secrets.yml
  sudo: yes
  tasks:
    - name: Add Brightbox PPA
      apt_repository: repo='ppa:brightbox/ruby-ng' state=present update_cache=true
    - name: Install Ruby
      apt: pkg={{item}} state=latest
      with_items:
        - "ruby{{ruby_version}}"
        - "ruby{{ruby_version}}-dev"
    - name: Create application user group
      group: name={{app_group_name}} gid={{app_user_gid}} state=present
    - name: Create application user
      user: name={{app_user_name}} uid={{app_user_uid}} group={{app_group_name}} home={{app_user_home}} shell=/bin/bash comment="CloudPort application user" state=present
    - name: Create application config
      template: src=../templates/config.j2 dest={{app_conf_file}} owner={{app_user_name}} group={{app_group_name}} mode=0640
    - name: Create application user home
      file: name={{app_user_home}} owner={{app_user_name}} group={{app_group_name}} mode=0750 state=directory
    - name: Create application data path
      file: name={{app_data_path}} owner={{app_user_name}} group={{app_group_name}} mode=0750 state=directory
    - name: Create application user log path
      file: name={{app_log_path}} owner={{app_user_name}} group=adm mode=0750 state=directory
    - name: Create application Upstart config
      template: src=../templates/upstart.conf.j2 dest={{app_upstart_file}} owner={{app_user_name}} group={{app_group_name}} mode=0644
