---
- hosts: cloudport
  vars:
  vars_files:
    - ../vars/globals.yml
    - ../vars/secrets.yml
  sudo: yes
  sudo_user: "{{app_user_name}}"
  tasks:
    - name: Install bundler
      gem: name=bundler version={{bundler_version}}
    - name: Create application user custom shell rc
      template: src=../templates/bashrc.j2
                dest={{app_user_bashrc}}
                owner={{app_user_name}}
                group={{app_group_name}}
                mode=0644
    - name: Create application user SSH config directory
      file:
        path: "{{app_user_ssh_config_dir}}"
        state: directory
        mode: 0755
    - name: Disable GitHub strict host key checking
      shell: "echo \"Host github.com\n\tStrictHostKeyChecking no\n\" >{{app_user_ssh_config_file}}"
      args:
        creates: "{{app_user_ssh_config_file}}"
    - name: Get application code from Git
      git: repo={{app_repo}} dest={{app_path}} version={{app_version}} force=yes
      notify:
        - Bundle install
        - Create database
        - Load database schema
        - Run database migrations
        - Ensure application PID directory
        - Reload application server
  handlers:
    - name: Bundle install
      shell: "{{bundle}} install --retry=5 --deployment --without '{{bundle_without}}'"
      args:
        chdir: "{{app_path}}"
    - name: Create database
      shell: "{{bundle}} exec rake db:create && touch {{db_created_flag}}"
      args:
        chdir: "{{app_path}}"
        creates: "{{db_created_flag}}"
    - name: Load database schema
      shell: "{{bundle}} exec rake db:schema:load && touch {{db_schema_loaded_flag}}"
      args:
        chdir: "{{app_path}}"
        creates: "{{db_schema_loaded_flag}}"
    - name: Run database migrations
      shell: "{{bundle}} exec rake db:migrate"
      args:
        chdir: "{{app_path}}"
    - name: Ensure application PID directory
      shell: "sudo {{app_pid_dir_script}}"
    - name: Reload application server
      shell: "sudo {{app_reload_script}}"
