---
- hosts: cloudport
  vars_files:
    - ../vars/secrets.yml
  become: yes
  tasks:
    - name: Install MySQL database server and related libraries
      apt: pkg={{ item }} state=latest
      with_items:
        - mariadb-server
        - mariadb-client
        - libmariadbclient-dev
        - python-mysqldb
    - name: Ensure MySQL enabled and started
      service: name=mysql enabled=yes state=started
    - name: Setup MySQL root user
      mysql_user: name=root
                  host={{ item }}
                  password={{ mysql_root_password }}
                  check_implicit_admin=yes
                  login_user=root
                  login_password={{ mysql_root_password }}
                  state=present
      with_items:
        - localhost
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
