---
- hosts: cloudport
  vars_files:
    - ../vars/secrets.yml
  sudo: yes
  tasks:
    - name: Install MySQL
      apt: pkg={{item}} state=latest
      with_items:
        - mariadb-server
        - mariadb-client
        - libmariadbclient-dev
      notify:
        - Start MySQL
    - name: Install Python interface to MySQL
      apt: pkg=python-mysqldb state=latest
    - name: Setup MySQL root user
      mysql_user: name=root
                  host={{item}}
                  password={{mysql_root_password}}
                  check_implicit_admin=yes
                  login_user=root
                  login_password={{mysql_root_password}}
                  state=present
      with_items:
        - localhost
        - "{{ansible_hostname}}"
        - 127.0.0.1
        - ::1
  handlers:
    - name: Start MySQL
      service: name=mysql state=started
