---
- hosts: all
  vars_files:
    - ../vars/globals.yml
    - ../vars/secrets.yml
  sudo: yes
  tasks:
    - name: Update operating system
      apt: upgrade=dist update_cache=yes dpkg_options='force-confold,force-confdef'
    - name: Install Git
      apt: pkg=git state=latest
    - name: Install node.js
      apt: pkg=nodejs state=latest
    - name: Install Nginx
      apt: pkg=nginx state=latest
      notify:
        - Start Nginx
  handlers:
    - name: Start Nginx
      service: name=nginx state=started
