---
- hosts: cloudport
  become: yes
  tasks:
    - name: Update Apt cache
      apt: update_cache=yes
    - name: Install unzip
      apt: pkg=unzip state=latest
    - name: Install development essentials
      apt: pkg={{ item }} state=latest
      with_items:
        - git
        - nodejs
        - build-essential
    - name: Install Nginx HTTP server/reverse proxy
      apt: pkg=nginx state=latest
    - name: Ensure Nginx service enabled and started
      service: name=nginx enabled=yes state=started
    - name: Install Redis in-memory data structure store
      apt: pkg=redis-server state=latest
    - name: Ensure Redis service enabled and started
      service: name=redis-server enabled=yes state=started
