---
- hosts: cloudport
  become: yes
  tasks:
    - name: Update operating system
      apt: upgrade=dist update_cache=yes
           dpkg_options='force-confold,force-confdef'
    - name: Install Git
      apt: pkg=git state=latest
    - name: Install Node.js
      apt: pkg=nodejs state=latest
    - name: Install build essentials
      apt: pkg=build-essential state=latest
    - name: Install Nginx
      apt: pkg=nginx state=latest
    - name: Ensure Nginx enabled and started
      service: name=nginx enabled=yes state=started
